const WORDS = {
  6: [
    "MAISON","JARDIN","SOLEIL","MIROIR","CHEVAL","BATEAU","VOYAGE","CARTON",
    "BOUGIE","CASIER","GAGNER","PERDRE","JOUEUR","COUSIN","VERGER","LAITUE",
    "PIGEON","RENARD","CASTOR","LIEVRE","GIRAFE","PANIER","SOURIS","MONTRE",
    "PLANTE","CACTUS","ETOILE","CAHIER","CRAYON","MOTEUR","ROUAGE","PALAIS",
    "EGLISE","ABBAYE","TEMPLE","PONTON","BARQUE","NAVIRE","PIRATE","TRESOR",
    "MEDUSE","REQUIN","HOMARD","PETALE","TULIPE","ROSIER","VIOLET","INDIGO",
    "ORANGE","DORURE","ARGENT","BRONZE","CUIVRE","CERISE","BANANE","RAISIN",
    "FRAISE","CITRON","MANGUE","LITCHI","AMANDE","TISANE","BEURRE","FARINE",
    "POIVRE","PERSIL","OIGNON","PATATE","TOMATE","COURGE","FOURMI","FRELON",
    "CIGALE","DESSIN","STATUE","ARCADE","BALCON","ETABLE","GRANGE","MOULIN",
    "FLEUVE","DESERT","SAVANE","VALLEE","PLAINE","CANYON","VOLCAN","GEYSER",
    "SOURCE","FOUDRE","ECLAIR","RAFALE","TYPHON","AURORE","SOIREE","SIECLE",
    "MINUTE","DRAGON","SIRENE","ESPRIT","SORTIE","ENTREE","BUREAU","DOUCHE",
    "LAVABO","CANAPE","CHAISE","RIDEAU","CABANE","CANARD","DINDON","MOUTON",
    "AGNEAU","COCHON","CHEVRE","JAGUAR","BUFFLE","FAUCON","PINSON","CARPES",
    "PERCHE","SANDRE","ROUGET","DORADE","DANSER","BALLES","TOUPIE","BILLES",
    "CARTES","JETONS","DOMINO","FLECHE","MASQUE","BOTTES","SABOTS","CASQUE",
    "BOURSE","PIECES","CHEQUE","COMPTE","BANQUE","CAISSE","TENDRE","FIDELE",
    "SECRET","LUTINS","TROLLS","DEMONS","REINES","PRINCE","NOBLES","BARONS",
    "COMTES","MOINES","PRETRE","PRIERE","CIERGE","ENCENS","FAMINE","PARFUM",
    "SAVONS","TIGRES","ZEBRES","SINGES","NAPPES","TRAINS","METROS","AVIONS",
    "FUSEES","ROUTES","CHEMIN","RANGER","POCHES","BAGUES","ANNEAU","LACETS",
    "BOUCLE","BARRES","PARLER","MARCHE","COURIR","SAUTER","PLEURS","RIVAGE",
    "VAGUES","PLAGES","DUNESS","ROCHES","CAVEAU","CAVERN","GROTTE","FALAIS",
    "ABYSSE","ABEILL","RUCHES","NICHES","TANIER","REPAIR","PRAIRI","TALUSS"
  ],
  7: [
    "MAISONS","JARDINS","SOLEILS","CHEVAUX","BATEAUX","VOYAGES","MUSIQUE","CARTONS",
    "BOUGIES","JOUEURS","COUSINS","BRANCHE","VERGERS","LAITUES","PIGEONS","RENARDS",
    "CASTORS","LIEVRES","GIRAFES","PANIERS","MONTRES","PLANTES","ETOILES","ECOLIER",
    "CAHIERS","CRAYONS","CHATEAU","TOMBEAU","EGLISES","ABBAYES","TEMPLES","PONTONS",
    "BARQUES","NAVIRES","PIRATES","TRESORS","MEDUSES","REQUINS","DAUPHIN","BALEINE",
    "HOMARDS","PETALES","PIVOINE","TULIPES","ROSIERS","BLANCHE","ARGENTS","BRONZES",
    "POMMIER","POIRIER","CERISES","BANANES","RAISINS","FRAISES","CITRONS","ABRICOT",
    "PRUNIER","MANGUES","LITCHIS","FIGUIER","AMANDES","CAFEINE","TISANES","FROMAGE",
    "YAOURTS","FARINES","SUCRIER","POIVRES","BASILIC","CIBOULE","OIGNONS","ECHALOT",
    "CAROTTE","PATATES","TOMATES","COURGES","POIVRON","BROCOLI","EPINARD","CRESSON",
    "ABEILLE","FRELONS","GRILLON","CIGALES","LIBELLE","PEINTRE","DESSINS","PALETTE",
    "PINCEAU","STATUES","COLONNE","ARCADES","PORTAIL","FENETRE","VITRAUX","BALCONS",
    "POTAGER","GRANGES","MOULINS","RIVIERE","FLEUVES","BARRAGE","DESERTS","SAVANES",
    "TOUNDRA","GLACIER","COLLINE","VALLEES","PLAINES","PLATEAU","CANYONS","VOLCANS",
    "CRATERE","GEYSERS","SOURCES","ORAGEUX","ECLAIRS","BRUMEUX","RAFALES","TORNADE",
    "OURAGAN","TYPHONS","CYCLONE","TEMPETE","AURORES","SOIREES","MATINEE","JOURNAL",
    "SEMAINE","SIECLES","MINUTES","SECONDE","FORTUNE","BONHEUR","DOUCEUR","COURAGE",
    "ROYAUME","EMPIRES","DRAGONS","SIRENES","ESPRITS","SORTIES","ENTREES","COULOIR",
    "CHAMBRE","CUISINE","BUREAUX","DOUCHES","CANAPES","CHAISES","ARMOIRE","COMMODE",
    "ETAGERE","RIDEAUX","GARAGES","CABANES","POULETS","CANARDS","DINDONS","MOUTONS",
    "AGNEAUX","COCHONS","CHEVRES","HAMSTER","JAGUARS","BUFFLES","CARIBOU","HERMINE",
    "CORBEAU","MOINEAU","MESANGE","BERGERS","CIGOGNE","MOUETTE","GOELAND","MANCHOT",
    "FAUCONS","PIVERTS","PINSONS","COLVERT","FOULQUE","FLAMANT","SPATULE","POMELOS",
    "NECTARS","BRUGNON","PAPAYES","GOYAVES","TRUITES","BROCHET","BARBEAU","GARDONS",
    "PERCHES","SANDRES","ABLETTE","TANCHES","MERLANS","ROUGETS","DORADES","ESPADON",
    "SARDINE","ANCHOIS","DANSEUR","TOUPIES","DOMINOS","FLECHES","MASQUES","ECHARPE",
    "CASQUES","POCHETT","BOURSES","BILLETS","CHEQUES","COMPTES","BANQUES","CAISSES",
    "MONNAIE","HEUREUX","TRISTES","JOYEUSE","TENDRES","TIMIDES","FIDELES","MENTEUR",
    "SECRETS","MYSTERE","ETRANGE","BIZARRE","FEERIES","PRINCES","BARONNE","ABBESSE",
    "PRETRES","EVEQUES","SAINTES","PRIERES","CIERGES","PARFUMS","VOITURE","BICYCLE",
    "ROUTIER","BRACELE","COLLIER","NUAGEUX","SOLAIRE","LUNAIRE","SAVANTE","CULTURE",
    "NATURES","CHANTRE","MESSAGE","CADEAUX","ARDOISE","TABLEAU","PLAFOND","PARQUET",
    "PLINTHE","SENTIER","TROUPEA","RIVAGES","VAGUESE","ROCHEUX","ABYSSES","CAVERNE",
    "GROTTES","FALAISE","ROUTINE","CHANTER","DESCEND","MONTANT","CONTEUR","ECRIVAI",
    "ACTEURS","DOCTEUR","AVOCATS","JUGESDE","TRIBUNS","REGENTS","PRINCES","BARONNE"
  ],
  8: [
    "JARDINER","VOYAGEUR","COUSINES","BRANCHES","CHATEAUX","TOMBEAUX","CHAPELLE","DAUPHINS",
    "BALEINES","PIVOINES","VIOLETTE","BLANCHIR","POMMIERS","POIRIERS","CERISIER","BANANIER",
    "FRAISIER","ABRICOTS","PRUNIERS","MANGUIER","FIGUIERS","NOISETTE","AMANDIER","FROMAGES",
    "SUCRIERE","BASILICS","CIBOULES","ECHALOTE","CAROTTES","POIVRONS","BROCOLIS","EPINARDS",
    "CRESSONS","ROQUETTE","ABEILLES","PAPILLON","GRILLONS","PEINTRES","DESSINER","PALETTES",
    "PINCEAUX","SCULPTER","COLONNES","PORTAILS","FENETRES","TERRASSE","POTAGERS","FERMETTE",
    "RIVIERES","BARRAGES","GLACIERS","MONTAGNE","COLLINES","PLATEAUX","CRATERES","ORAGEUSE",
    "TONNERRE","BRUMEUSE","TORNADES","OURAGANS","CYCLONES","TEMPETES","MATINEES","JOURNAUX",
    "SEMAINES","HEUREUSE","SECONDES","FORTUNES","BONHEURS","DOUCEURS","JEUNESSE","GRANDEUR",
    "COURAGES","RICHESSE","PAUVRETE","VICTOIRE","DEFAITES","GUERRIER","CAVALIER","ROYAUMES",
    "TIGRESSE","MAGIQUES","COULOIRS","CHAMBRES","CUISINES","FAUTEUIL","ARMOIRES","COMMODES",
    "ETAGERES","CHEMINEE","LAPINEAU","HAMSTERS","ECUREUIL","CARIBOUS","SANGLIER","BLAIREAU",
    "HERMINES","CHOUETTE","CORBEAUX","MOINEAUX","MESANGES","CIGOGNES","MOUETTES","GOELANDS",
    "ALBATROS","MANCHOTS","SARCELLE","COLVERTS","FOULQUES","AIGRETTE","FLAMANTS","SPATULES",
    "RUTABAGA","BRUGNONS","MYRTILLE","BROCHETS","BARBEAUX","ABLETTES","ESPADONS","SARDINES",
    "CARTABLE","PEUPLIER","CIMETIER","TROMBONE","UNIFORME","FORGERON","ORCHIDEE","QUERELLE",
    "TROTTOIR","VOLATILE","JUMELAGE","KILOWATT","LANGOUST","RUSTIQUE","VAGABOND","CHAMPION",
    "DELICATE","HABITANT","LACUSTRE","MARITIME","NAUTIQUE","CLAIRIER","HEROIQUE","ILLIMITE",
    "KARATEKA","MACHINAL","OISILLON","QUALIFIE","VACANCIE","FOSSETTE","INDOLENT","NATURIST",
    "OUVRAGEE","ZIBELINE","ALPHABET","BALADEUR","CHARMANT","IMMUNITE","LAITERIE","PEPINIER",
    "TRIPLETT","ATTENTIV","BERCEUSE","EFFICACE","FANTASME","IDENTITE","MENSONGE","ODORATIF",
    "REFUGIEE","TROUPEAU","URBANISE","BOUTEILL","CIVILISE","FRANCAIS","GENERALE","PERSONNE",
    "ASSASSIN","BIENFAIT","CONVAINC","FELICITE","HUMANIST","JOURNEES","CADENCES","BRAVOURE",
    "COQUETTE","DANSEUSE","ECRIVAIN","FACTEURS","GUITARES","JONGLEUR","LECTURES","MARIAGES",
    "NAVETTES","OCCUPANT","ROULETTE","SOULAGER","TENDANCE","UTILISER","ACHETEUR","BAIGNEUR",
    "CALCULER","DEMARRER","EFFRAYER","FROISSER","GALETTES","HABITUEL","JOURNALI","LANGAGES",
    "MARMITES","NOUVELLE","OUBLIETT","PARLEUSE","QUITTANT","RAISINEE","SOIGNEUS","TUTOYAGE",
    "VAINQUER","ANGOISSE","BALEINON","CALEMBOU","DELESTER","ECLAIRER","FOURRURE","GLISSADE",
    "HAUTEURS","INFAMIES","JONGLEUR","LIVRAISO","MOMENTUM","NORMALES","ORANGEER","PIVOINEE",
    "QUERELLE","RICHESSE","SAUMONNE","TABLETTE","UTILISER","VINAIGRE","ZIBELINE","AROMATES"
  ],
  9: [
    "AVENTURES","BATAILLES","CAPITAINE","ELEPHANTS","FORMATION","HARMONIES","INDUSTRIE","KILOMETRE",
    "MARMELADE","PASSAGERS","QUARTIERS","SOUVENIRS","TELEPHONE","UNIVERSEL","XYLOPHONE","BARRICADE",
    "FANTAISIE","INFIRMIER","JONGLERIE","LIBRAIRIE","MAGICIENS","NOSTALGIE","OUVERTURE","CHANTEUSE",
    "GEOMETRIE","NETTOYAGE","OPTIMISTE","PATISSIER","QUOTIDIEN","SCULPTEUR","TROMBONES","UNIFORMES",
    "VIGNOBLES","AVALANCHE","BOULEVARD","CASCADEUR","DEFINITIF","ESCARGOTS","FORGERONS","GRENADIER",
    "INVENTEUR","JONQUILLE","MOUSTACHE","ORCHIDEES","PARAPLUIE","QUERELLES","REGISSEUR","TROTTOIRS",
    "VOLATILES","BIENVENUE","CHEMINEES","DELICIEUX","INTERVIEW","JUMELAGES","KILOWATTS","LANGOUSTE",
    "OBSCURITE","PHARMACIE","QUEBECOIS","RUSTIQUES","SUBLIMITE","TENDRESSE","ULTIMATUM","VAGABONDS",
    "AERONAUTE","CHAMPIONS","DELICATES","EMISSAIRE","HABITANTS","ISOLATION","JARDINIER","LACUSTRES",
    "MARITIMES","NAUTIQUES","PERMANENT","STATIONNE","TENDANCES","ULTRASONS","CLAIRIERE","DEBARQUER",
    "FORTUITES","GROSSESSE","HEROIQUES","ILLIMITES","KARATEKAS","MACHINALE","NUMERIQUE","OISILLONS",
    "PRESQUILE","QUALIFIES","VACANCIER","ABREUVOIR","BRIQUETER","CHATAIGNE","FOSSETTES","HASARDEUX",
    "INDOLENTE","NATURISTE","OUVRAGEES","RIGOUREUX","SOIGNEUSE","VENTILEUR","ZIBELINES","ALPHABETS",
    "BALADEURS","CHARMANTS","DIVERSITE","IMMUNITES","LAITERIES","NORMANDIE","PEPINIERE","QUINTUPLE",
    "RAYONNAGE","TRIPLETTE","UNANIMITE","ATTENTIVE","BERCEUSES","CALEMBOUR","EFFICACES","FANTASMES",
    "HONNETETE","IDENTITES","JOYEUSETE","MENSONGES","QUITTANCE","REFUGIEES","SOULIGNER","TROUPEAUX",
    "ACQUITTER","BOUTEILLE","CIVILISES","FRANCAISE","GENERALES","HORLOGERS","IMMENSITE","JURIDIQUE",
    "PERSONNES","RAISONNER","SERVITEUR","TEMERAIRE","VARIATION","ASSASSINE","BIENFAITS","CONVAINCU",
    "DELIBEREE","FELICITES","GUERRIERE","HUMANISTE","INFLUENCE","MERVEILLE","NAISSANCE","PEINTURES",
    "RACONTANT","TENTATION","UTILEMENT","VIRGINITE","CALENDRIE","FLEURISTE","GAILLARDE","INTERDITS",
    "JONCTIONS","LANCEMENT","PRETENDUS","QUATRIEME","TROUVAILL","ACCROITRE","DETERMINE","ELOIGNEES",
    "FINANCIER","INTERESSE","JUSTIFIER","KILOGRAMM","MELANGEUR","ORGANISER","PARFUMEES","REPONDEUR",
    "SOLIDITES","TARTELETT","ALLUMETTE","BERGERIES","CHARRETTE","DOUCEMENT","ECRITURES","GARNITURE",
    "INSTALLER","LIBERTINE","MARTELAGE","NAPOLEONS","OUBLIEUSE","PORTILLON","VENGEANCE","CAVALIERE",
    "DENONCEES","ECRIVAINS","INSTRUITE","MERIDIENS","NEGLIGENT","ORANGERIE","RAPATRIES","SAUMONNEE",
    "TENTACULE","ABANDONNE","BAIGNOIRE","CARROSSER","DEVELOPPE","EQUILIBRE","FRANCHISE","HARMONISE",
    "JACQUERIE","LIMONADES","MENESTREL","NOURRICES","PRIVATION","REMARQUER","SOUFFLEUR","ALIMENTER",
    "CALMEMENT","ESCALIERS","FRAICHEUR","HONORAIRE","IDEALISER","LITTORALE","MAGNIFIES","NUMEROTER",
    "ORANGEADE","PARFAITES","RESONANCE","SACRIFICE","TROUSSEAU","UTILISERA","VENDREDIS","WAGONNETS",
    "ZEPHYRSDE","ARCHITECT","BIBELOTES","CITADELLE","DENIVELES","ECOLOGIES","FRELATEES","GUITARIST"
  ]
};

function _normalize(s) {
  return s.normalize("NFD").replace(/[̀-ͯ]/g, "").toUpperCase();
}

for (const k of Object.keys(WORDS)) {
  const len = parseInt(k, 10);
  const seen = new Set();
  WORDS[k] = WORDS[k]
    .map(_normalize)
    .filter(w => w.length === len && /^[A-Z]+$/.test(w))
    .filter(w => { if (seen.has(w)) return false; seen.add(w); return true; });
}

function pickRandomWord(length) {
  const pool = WORDS[length] || [];
  if (pool.length === 0) return null;
  const won = (window.MotusStats && window.MotusStats.getWonWords)
    ? window.MotusStats.getWonWords(length)
    : [];
  const wonSet = new Set(won);
  let remaining = pool.filter(w => !wonSet.has(w));
  let cycled = false;
  if (remaining.length === 0) {
    if (window.MotusStats && window.MotusStats.resetWonWords) {
      window.MotusStats.resetWonWords(length);
    }
    remaining = pool.slice();
    cycled = true;
  }
  const word = remaining[Math.floor(Math.random() * remaining.length)];
  return { word, cycled };
}

function isValidWord(word) {
  const w = _normalize(word);
  if (!/^[A-Z]+$/.test(w)) return false;
  return WORDS[w.length] && WORDS[w.length].includes(w);
}

window.MotusWords = { WORDS, pickRandomWord, isValidWord };
